---
  all: # main group
    hosts:
      10.116.0.4:
      10.116.0.2:
    children:
      HOST1: # group name  
        hosts: 
          10.116.0.4:
      HOST2:
        hosts:
          10.116.0.2: