---
- name: Daily Class Task
  hosts: localhost
  tasks:
    - name: first file
      file:
        path: "/tmp/file1"
        state: touch
        mode: u+x,g+wx
    - name: second file
      file:
        path: "/tmp/file2"
        state: touch
        mode: u+x,g+wx
      
      
      