--- # start of a yaml file
- name: My first play # this is my optional line, this is name of play
  hosts: localhost    # this is the target
  tasks:
    - name: Task1     # this is optional line, this is task1
      command: "ls -l /etc"
    - name: Task2
      group: 
        name: amy
        gid: 2500
    - name: Task3
      user:
        name: amy
        uid: 2500
        group: 
    - name: task4
      file:
        path: "/tmp/testfile1"
        state: touch
        mode: u+x,g+wx,o+x
        owner: amy
        group: amy
        